INSERT INTO `ENTRETERIMENTO` (`ID`, `NOME`, `TIPO`, `DIRETOR`, `ATOR_PRINCIPAL`, `ATRIZ_PRINCIPAL`, `ANO_LANCAMENTO`, `DURACAO_MINUTOS`, `CLASSIFICACAO_ETARIA`, `GENERO`, `NACIONALIDADE`, `RANKING`, `RANKING_TIPO`, `RANKING_NOME`) VALUES
(1, 'Stranger Things', 'SÃ‰RIE', 'IrmÃ£os Duffer', 'Millie Bobby Brown', 'Winona Ryder', 2016, 60, '16+', 'Suspense', 'Estados Unidos', 22, 'Mundial', 'Netflix'),
(2, 'Black Mirror', 'SÃ‰RIE', 'Charlie Brooker', 'Bryce Dallas Howard', 'Hayley Atwell', 2011, 45, '18+', 'FicÃ§Ã£o CientÃ­fica', 'Reino Unido', 25, 'Mundial', 'Netflix'),
(3, 'The Irishman', 'FILME', 'Martin Scorsese', 'Robert De Niro', 'Anna Paquin', 2019, 209, '16+', 'Crime', 'Estados Unidos', 21, 'Mundial', 'Netflix'),
(4, 'Breaking Bad', 'SÃ‰RIE', 'Vince Gilligan', 'Bryan Cranston', 'Aaron Paul', 2008, 45, '18+', 'Drama', 'Estados Unidos', 29, 'Mundial', 'Netflix'),
(5, 'The Crown', 'SÃ‰RIE', 'Peter Morgan', 'Jonathan Pryce', 'Olivia Colman', 2016, 60, '16+', 'Drama', 'Reino Unido', 8, 'Mundial', 'Netflix'),
(6, 'Inception', 'FILME', 'Christopher Nolan', 'Leonardo DiCaprio', 'Ellen Page', 2010, 148, '14+', 'AÃ§Ã£o', 'Estados Unidos', 24, 'Mundial', 'Netflix'),
(7, 'Friends', 'SÃ‰RIE', 'James Burrows', 'Jennifer Aniston', 'Matthew LeBlanc', 1994, 22, 'Livre', 'ComÃ©dia', 'Brasil', 25, 'Mundial', 'Netflix'),
(8, 'The Godfather', 'FILME', 'Francis Ford Coppola', 'Marlon Brando', 'Al Pacino', 1972, 175, '16+', 'Crime', 'Estados Unidos', 14, 'Mundial', 'Netflix'),
(9, 'La Casa de Papel', 'SÃ‰RIE', 'Ãlex Pina', 'Ãšrsula CorberÃ³', 'Ãlvaro Morte', 2017, 50, '16+', 'Drama', 'Espanha', 31, 'Mundial', 'Netflix'),
(10, 'Pulp Fiction', 'FILME', 'Quentin Tarantino', 'John Travolta', 'Uma Thurman', 1994, 154, '18+', 'Crime', 'Estados Unidos', 3, 'Mundial', 'Netflix'),
(11, 'The Witcher', 'SÃ‰RIE', 'Lauren Schmidt Hissrich', 'Henry Cavill', 'Anya Chalotra', 2019, 60, '16+', 'Fantasia', 'Estados Unidos', 30, 'Mundial', 'Netflix'),
(12, 'The Matrix', 'FILME', 'Lana Wachowski e Lilly Wachowski', 'Keanu Reeves', 'Carrie-Anne Moss', 1999, 136, '14+', 'AÃ§Ã£o', 'Estados Unidos', 29, 'Mundial', 'Netflix'),
(13, 'Money Heist', 'SÃ‰RIE', 'Ãlex Pina', 'Ãšrsula CorberÃ³', 'Ãlvaro Morte', 2017, 50, '16+', 'Crime', 'Brasil', 20, 'Mundial', 'Netflix'),
(14, 'Forrest Gump', 'FILME', 'Robert Zemeckis ', 'Tom Hanks ', 'Robin Wright', 1994, 142, '12+ ', 'Drama', 'Estados Unidos', 10, 'Mundial', 'Netflix'),
(15, 'Vikings ', 'SÃ‰RIE', 'Michael Hirst', 'Travis Fimmel', 'Katheryn Winnick', 2013, 44, '18+ ', 'Drama', 'Brasil', 26, 'Mundial', 'Netflix'),
(16, 'The Dark Knight ', 'FILME', 'Christopher Nolan ', 'Christian Bale ', 'Heath Ledger ', 2008, 152, '14+ ', 'AÃ§Ã£o', 'Estados Unidos', 26, 'Mundial', 'Netflix'),
(17, 'Greyâ€™s Anatomy ', 'SÃ‰RIE', 'Shonda Lynn Rhimes', 'Patrick Dempsey', 'Katherine Heigl', 2005, 41, '14+ ', 'Drama', 'Brasil', 16, 'Mundial', 'Star'),
(18, 'The Shawshank Redemption ', 'FILME', 'Frank Darabont ', 'Tim Robbins ', 'Morgan Freeman ', 1994, 142, '16+ ', 'Drama', 'Estados Unidos', 2, 'Mundial', 'HBO'),
(19, 'Gladiador ', 'FILME', 'Ridley Scott ', 'Tim Robbins ', 'Connie Nielsen ', 2000, 155, '16+ ', 'AÃ§Ã£o/Drama', 'Brasil', 36, 'Mundial', 'Amazon Prime'),
(20, 'O Senhor dos AnÃ©is: A Sociedade do Anel ', 'FILME', 'Peter Jackson ', 'Elijah Wood ', 'Liv Tyler ', 2001, 178, '12+ ', 'Aventura/Fantasia', 'Estados Unidos', 25, 'Mundial', 'Disney'),
(21, 'Clube da Luta ', 'FILME', 'David Fincher ', 'Brad Pitt ', 'Helena Bonham Carter ', 1999, 139, '18+ ', 'Drama', 'Brasil', 18, 'Mundial', 'Disney'),
(22, 'Cidade de Deus ', 'FILME', 'Fernando Meirelles e KÃ¡tia Lund ', 'Alexandre Rodrigues ', 'Alice Braga ', 2002, 130, '18+ ', 'Crime/Drama', 'Brasil', 14, 'Mundial', 'HBO'),
(23, 'Kill Bill: Volume 1 ', 'FILME', 'Quentin Tarantino ', 'David Carradine ', 'Uma Thurman ', 2003, 111, '16+ ', 'AÃ§Ã£o/Thriller', 'Estados Unidos', 17, 'Mundial', 'HBO'),
(24, 'Entrevista com o Vampiro ', 'FILME', 'Neil Jordan ', 'Brad Pitt ', 'Tom Cruise ', 1994, 123, '16+ ', 'AÃ§Ã£o/Thriller', 'Estados Unidos', 2, 'Mundial', 'Disney'),
(25, 'Bastardos InglÃ³rios ', 'FILME', 'Quentin Tarantino ', 'Brad Pitt ', 'Melanie Laurentz  ', 2009, 153, '18+ ', 'Drama/Guerra', 'Estados Unidos', 36, 'Mundial', 'Amazon Prime'),
(26, 'Sr. e Sra. Smith ', 'FILME', 'Doug Liman ', 'Brad Pitt ', 'Angelina Jolie ', 2005, 120, '14+ ', 'AÃ§Ã£o/ComÃ©dia', 'Estados Unidos', 24, 'Mundial', 'Amazon Prime'),
(27, 'Tropa de Elite ', 'FILME', 'JosÃ© Padilha ', 'Wagner Moura ', 'Maria Ribeiro ', 2007, 115, '18+ ', 'AÃ§Ã£o/Drama', 'Estados Unidos', 10, 'Mundial', 'Amazon Prime'),
(28, 'Central do Brasil ', 'FILME', 'Walter Salles ', 'VinÃ­cius de Oliveira ', 'Fernanda Montenegro ', 1998, 113, 'livre', 'Drama', 'Estados Unidos', 15, 'Mundial', 'Disney'),
(29, 'O Auto da Compadecida ', 'FILME', 'Guel Arraes ', 'Matheus Nachtergaele ', 'Denise Fraga ', 2000, 104, '12+ ', 'ComÃ©dia/Drama', 'Brasil', 8, 'Mundial', 'Disney'),
(30, 'Sr. e Sra. Smith ', 'FILME', 'Doug Liman ', 'Brad Pitt ', 'Angelina Jolie ', 2005, 120, '14+ ', 'AÃ§Ã£o/ComÃ©dia', 'Estados Unidos', 32, 'Mundial', 'Netflix'),
(31, 'O Senhor dos AnÃ©is: As Duas Torres', 'FILME', 'Peter Jackson', 'Elijah Wood', 'Liv Tyler', 2002, 201, '12+', 'Aventura/Fantasia', 'Nova ZelÃ¢ndia', 21, 'Nacional', 'Netflix'),
(32, 'The Boys', 'FILME', 'Eric Kripke', 'Karl Urban', 'Erin Moriarty', 2019, 202, '16+', 'AÃ§Ã£o/Drama', 'Estados Unidos', 22, 'Nacional', 'Conhecido'),
(33, 'Mad Max: Estrada da FÃºria', 'FILME', 'George Miller', 'Tom Hardy', 'Charlize Theron', 2015, 203, '18+', 'AÃ§Ã£o/Aventura', 'AustrÃ¡lia', 21, 'Nacional', 'Amazon Prime'),
(34, 'The Marvelous Mrs. Maisel', 'FILME', 'Amy Sherman-Palladino', 'Rachel Brosnahan', 'Alex Borstein', 2017, 204, '18+', 'ComÃ©dia/Drama', 'Estados Unidos', 22, 'Nacional', 'Amazon Prime'),
(35, 'Matrix Reloaded', 'FILME', 'Lana Wachowski e Lilly Wachowski', 'Keanu Reeves', 'Carrie-Anne Moss', 2003, 205, '18+', 'AÃ§Ã£o/FicÃ§Ã£o CientÃ­fica', 'Estados Unidos', 21, 'Nacional', 'Netflix'),
(36, 'Deadpool', 'FILME', 'Tim Miller', 'Ryan Reynolds', 'Morena Baccarin', 2016, 206, '18+', 'AÃ§Ã£o/ComÃ©dia', 'Estados Unidos', 22, 'Nacional', 'Netflix'),
(37, 'Homem aranha', 'FILME', 'Sam Raimi', 'Tobey Maguire', 'Kirsten Dunst', 2006, 90, '16+', 'AÃ§Ã£o', 'Estados Unidos', 7, 'Mundial', 'Conhecido');
